### ISSUE TITLE
BUG: Renaming species

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/Core#41]
iBioSim Version 2.8.1

Operating system: Windows 8.1

Bug reported by: calliclark24@gmail.com

Description:
I attempted to rename a species but that name already existed as a variable

Stack trace:
java.lang.IllegalArgumentException: org.sbml.jsbml.IdentifierException: Cannot set duplicate identifier Glyph__AHL for speciesGlyph.
	at org.sbml.jsbml.AbstractNamedSBase.setId(AbstractNamedSBase.java:289)
	at biomodel.parser.BioModel.changeSpeciesId(BioModel.java:3283)
	at biomodel.gui.sbmlcore.SpeciesPanel.handlePanelData(SpeciesPanel.java:884)
	at biomodel.gui.sbmlcore.SpeciesPanel.constructor(SpeciesPanel.java:583)
	at biomodel.gui.sbmlcore.SpeciesPanel.<init>(SpeciesPanel.java:70)
	at biomodel.gui.schematic.ModelEditor.launchSpeciesPanel(ModelEditor.java:1903)
	at biomodel.gui.sbmlcore.MySpecies.mouseClicked(MySpecies.java:1123)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.sbml.jsbml.IdentifierException: Cannot set duplicate identifier Glyph__AHL for speciesGlyph.
	at org.sbml.jsbml.AbstractNamedSBase.setId(AbstractNamedSBase.java:287)
	... 38 more

**Comment by buggsley** [comment]
Hi,

I'm not able to reproduce this one.  Can you?  If so, can you give me more
detailed steps?

Thanks,

Chris
