### ISSUE TITLE
BUG: Species editor inaccessible after model renaming

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/Core#44]
iBioSim Version 2.8.1

Operating system: Linux

Bug reported by: myers@ece.utah.edu

Description:

Stack trace:
java.lang.NullPointerException
	at biomodel.gui.schematic.BioGraph.updateInternalPosition(BioGraph.java:1587)
	at biomodel.gui.schematic.Schematic$11.invoke(Schematic.java:1292)
	at com.mxgraph.util.mxEventSource.fireEvent(Unknown Source)
	at com.mxgraph.util.mxEventSource.fireEvent(Unknown Source)
	at com.mxgraph.view.mxGraph.cellsMoved(Unknown Source)
	at com.mxgraph.view.mxGraph.moveCells(Unknown Source)
	at com.mxgraph.swing.handler.mxGraphHandler.moveCells(Unknown Source)
	at com.mxgraph.swing.handler.mxGraphHandler.mouseReleased(Unknown Source)
	at com.mxgraph.swing.handler.mxGraphHandler.drop(Unknown Source)
	at javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1279)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:537)
	at sun.awt.X11.XDropTargetContextPeer.processDropMessage(XDropTargetContextPeer.java:184)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:851)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:775)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4727)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4566)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4417)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by buggsley** [comment]
Hi Chris,
Sorry I was the one who reported the bug, but I mistakenly put your email
instead of mine.
I'm running the java version on Linux, and tried to rename the model, then get
back to the schematic 
workspace and click on the promoter to edit it, but an exception popped out
saying "unhandled exception". 
I couldn't reproduce it, but last time I encountered it, I just had to restart
iBioSim to get access to the editor 
again.
Trang
