### ISSUE TITLE
BUG: startup

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/Core#45]
iBioSim Version 2.8

Operating system: Windows 8.1

Bug reported by: dan.cariello@gmail.com

Description:
throws exception to on startup

Stack trace:
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(Unknown Source)
	at main.Gui.<init>(Gui.java:411)
	at main.Gui.main(Gui.java:8064)

**Comment by buggsley** [comment]
Please make sure you are using Version 2.8.1.  There were some problems with
2.8.

Chris
