### ISSUE TITLE
BUG: Problems creating Model File

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/Core#48]
iBioSim Version 2.8.2

Operating system: Mac OS X

Bug reported by: andy.gilbert@utah.edu

Description:
I recently got a macbook pro. I tried to install iBioSim on it and the install worked fine. However, I am having trouble creating model files now as it throws this exception. This happens on both the java version and the regular os x version.

Stack trace:
java.lang.UnsupportedClassVersionError: com/mxgraph/model/mxICell : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at biomodel.gui.schematic.ModelEditor.buildGui(ModelEditor.java:1551)
	at biomodel.gui.schematic.ModelEditor.<init>(ModelEditor.java:193)
	at main.Gui.createModel(Gui.java:4078)
	at main.Gui.actionPerformed(Gui.java:2921)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:337)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:778)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1645)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2859)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:670)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:678)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:678)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:678)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:678)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:649)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:267)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:254)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2936)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2928)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2822)
	at java.awt.Component.processEvent(Component.java:6191)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1856)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:722)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1000)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:865)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:686)
	at java.awt.Component.dispatchEventImpl(Component.java:4648)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by buggsley** [comment]
This is usually due to running with an older Java version.  Any chance you are
using a JDK older than 1.6?

Chris

**Comment by buggsley** [comment]
Actually, it seems that particular library needs Java 7.

Chris

**Comment by buggsley** [comment]
Did you get this working?

Chris

**Comment by buggsley** [comment]
I have Java 8 installed. Do I need to revert to the previous version?

Andy

**Comment by buggsley** [comment]
Exact build:

|Andy| @ ~ > java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
|Andy| @ ~ >=20

Let me know if you need any additional information. I would be happy to =
provide it. In the meantime I will continue to develop my models on my =
old computer.=20

Andy

> On Feb 12, 2015, at 5:37 PM, Chris Myers =

**Comment by buggsley** [comment]
No, it was able to generate the model now, but it was running into issues when I was trying to follow the tutorial. I think I need to find where the java 8 library was installed and point the launcher to there rather than to the web version. the web version probably has some differences which are effecting the tool.

**Comment by buggsley** [comment]
Dr. Myers,=20

I was able to install the latest version of java so that when I type =
java -version in the terminal it now reads 1.8. However, I am still =
having problems with the learn view. When I try to get it to learn the =
model from the tutorial I get the following error:

Do you have any suggestions for this problem? You may notice that there =
are no values in the bins. It was unable to autocomplete values when I =
clicked suggest levels. However, this error occurred when I manually =
entered levels or clicked auto-generate levels. This error also occurred =
with both the java version and the mac version of iBioSim.=20

Thanks,
Andy

> On Feb 18, 2015, at 9:43 AM, Chris Myers =
