### ISSUE TITLE
BUG: Error thrown out when opening a project containing a model
 labeled 3BinRun1

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/Core#53]
iBioSim Version 2.8.2

Operating system: Windows 8.1

Bug reported by: adrian.shimpi@utah.edu

Description:
When choosing to open either with the open or open recent options a project folder with a model named 3BinRun1 it throws the error.

Stack trace:
java.lang.IllegalArgumentException: "3BinRun1" is not a valid identifier for this model.
	at org.sbml.jsbml.AbstractNamedSBase.checkIdentifier(AbstractNamedSBase.java:164)
	at org.sbml.jsbml.AbstractNamedSBase.setId(AbstractNamedSBase.java:283)
	at org.sbml.jsbml.AbstractNamedSBase.<init>(AbstractNamedSBase.java:146)
	at org.sbml.jsbml.AbstractNamedSBase.<init>(AbstractNamedSBase.java:133)
	at org.sbml.jsbml.Model.<init>(Model.java:311)
	at org.sbml.jsbml.SBMLDocument.createModel(SBMLDocument.java:544)
	at biomodel.parser.BioModel.createSBMLDocument(BioModel.java:147)
	at biomodel.parser.BioModel.loadSBMLFile(BioModel.java:6649)
	at biomodel.parser.BioModel.load(BioModel.java:3109)
	at main.util.FileTree.addNodes(FileTree.java:274)
	at main.util.FileTree.<init>(FileTree.java:142)
	at main.Gui.refresh(Gui.java:5763)
	at main.Gui.actionPerformed(Gui.java:2872)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by buggsley** [comment]
A model name starting with a number is illegal.  Not sure how you created this. 
Can you reproduce?  If so, 
how?  Also, you should be able to rename the file to open it.  Might need to
also change the model id.  If 
you need help doing this, please send me the file.

Chris
