### ISSUE TITLE
BUG: Error thrown when creating a promoter

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/Core#54]
iBioSim Version 2.8.3

Operating system: Mac OS X

Bug reported by: andy.gilbert@utah.edu

Description:
Following the tutorial with version 2.8.3 and when I tried to create a promoter with custom values it gave an error

Stack trace:
java.lang.NullPointerException
	at biomodel.parser.BioModel.changePromoterId(BioModel.java:3175)
	at biomodel.gui.gcm.PromoterPanel.openGui(PromoterPanel.java:475)
	at biomodel.gui.gcm.PromoterPanel.<init>(PromoterPanel.java:335)
	at biomodel.gui.schematic.ModelEditor.launchPromoterPanel(ModelEditor.java:1874)
	at biomodel.gui.schematic.Schematic.bringUpEditorForCell(Schematic.java:2764)
	at biomodel.gui.schematic.Schematic$9.mouseReleased(Schematic.java:1182)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by buggsley** [comment]
I was not able to reproduce this one.  Can you?  If so, please let me know what
steps you took or send me 
the model which is causing the problem.

Thanks,

Chris
